### ISSUE TITLE
Parser Failure under certain backticks

### ISSUE THREAD

**Issue by mariari** [carpentry-org/gt4carp#12]
I've gotten errors when trying to run `CarpFile >> coreLodStatements`

I diagnosed the issue to being a parser error:

![](https://pomf2.lain.la/f/nlrhnjlr.png)
 
Namely it seems that for some reason the `(cons` is not considered a place to close the paren)

![](https://pomf2.lain.la/f/vhor2ifq.png)

When removing the `(set! ...)` this fixes both the highlighting on the `((set! ...)` and the parse error that was run into.

![](https://pomf2.lain.la/f/xv0e3im5.png)

**Comment by hellerve** [comment]
Thanks for the bug report! Just a bit of preliminary investigation: it seems to work fine with a single quasi-quotation, but if I put two in, the token instead becomes a `SmaCCPatternNode`, which is a different token internal to SmaCC. I assume that I’m doing something wrong by inheriting from the wrong class or not disabling a feature I do not want. I’ll look into it. Good catch! <img width="1728" alt="Bildschirmfoto 2024-10-09 um 09 26 03" src="https://github.com/user-attachments/assets/467bc683-341a-4c47-a19e-91f19984c341">
<img width="1728" alt="Bildschirmfoto 2024-10-09 um 09 28 17" src="https://github.com/user-attachments/assets/b7584dce-9238-4e60-809c-7436c5f7a76f">
